### ISSUE TITLE
Manifest preview is highlighting the entire column instead of the invalid cell

### ISSUE THREAD

**Issue by xindiguo** [Sage-Bionetworks/data_curator#70] opened 2020-06-06 00:28 UTC
Entire column was highlighted when one of the cells in the column is invalid.

**Comment by rrchai** [comment] 2021-07-23 16:43
The issue should be fixed, since I cannot reproduce it. Feel free to re-open if the behavior still happen on your end.

**Closed by rrchai** 2021-07-23 16:43 UTC
Labels: feature, good first issue
