### ISSUE TITLE
Attempting to annotate deleted file causes app to crash

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/data_curator#188] opened 2021-08-25 15:56 UTC
A user today generated a manifest, annotated some files, deleted a file, and then tried to submit a manifest that included the deleted file as a row. When she went to validate, it worked fine, but when she went to submit, the app crashed (the typical Shiny 'Disconnected from app' error). 

Looking at the logs is how I discovered the app was trying to annotate a deleted file: 

```
Warning: Error in py_call_impl: SynapseHTTPError: 404 Client Error:
Entity syn26075076 is in trash can.
```

The app should handle this situation more gracefully, maybe first with a check to ensure that all files in the manifest are "live" on synapse (in which case, maybe this should be schematic functionality), or at least detecting the 404 error and presenting it to the user.

**Comment by milen-sage** [comment] 2021-08-25 16:16
@allaway thanks for filing this! In other projects we don't allow users/teams to delete entities directly themselves, and handling this use case was not prioritized. It's a good time to revisit and add a feature to schematic.

It sounds like you are suggesting surfacing a warning message during validation, in addition to handling annotations for missing entities in schematic; e.g. instead of crashing :) we can skip annotating for all missing entities.

**Comment by adamjtaylor** [comment] 2022-07-06 19:13
This also looks to have been the cause of the crash that HTAN Duke users were seeing as reported in [HTAN-92](https://sagebionetworks.jira.com/jira/servicedesk/projects/HTAN/queues/custom/1/HTAN-92)

**Comment by GiaJordan** [comment] 2022-08-29 20:19
Following up on closure, annotation is skipped for deleted entities during the annotation process. Addressed with [#587](https://github.com/Sage-Bionetworks/schematic/issues/587) in [#871](https://github.com/Sage-Bionetworks/schematic/pull/871)
@adamjtaylor

**Comment by milen-sage** [comment] 2022-08-29 23:34
And I believe this is part of schematic [22.08.1](https://github.com/Sage-Bionetworks/schematic/pull/877) on pypi.

**Comment by adamjtaylor** [comment] 2022-09-08 12:41
Validating that this is fixed for HTAN

- Created [test-deleted-files](https://www.synapse.org/#!Synapse:syn35903908) folder in HTAN Center C
- Uploaded test file `IMG_2938 Large.jpeg` as [syn35903959](https://www.synapse.org/#!Synapse:syn35903959)
- Add second file to folder `IMG_2712 Large.jpeg` as [syn35906086](https://www.synapse.org/#!Synapse:syn35906086)
- Generated template in HTAN DCA staging with `Other Assay` component
- Completed template and submitted metadata - SUCCESS
- Deleted one test file `IMG_2938 Large.jpeg` / [syn35903959](https://www.synapse.org/#!Synapse:syn35903959)
- Reload DCA and attempt to resubmit manifest with both files listed
    - DCA report SUCCESS with no warnings or errors

So the crash is fixed but I think it would be important to add a warning that deleted files have been skipped.

**Comment by milen-sage** [comment] 2022-09-08 15:48
Thanks @adamjtaylor - that's great news! Yes, we'll open a new issue for a 'warning enhancement'.

**Comment by milen-sage** [comment] 2022-09-12 14:41
Will include^ in the issue.

**Comment by milen-sage** [comment] 2022-10-11 14:57
Closing this issue, subsequent work on warning will be tracked in a new one.

**Closed by milen-sage** 2022-10-11 14:57 UTC
Labels: bug
