### ISSUE TITLE
Error handle mismatch in selected vs submitted schema 

### ISSUE THREAD

**Issue by xdoan** [Sage-Bionetworks/data_curator#61] opened 2020-05-20 17:50 UTC
Better error output for mismatch in selected vs submitted  which results in "wrong schema" error upon validation. 

Features (building on Milen's comment below):
- [ ] 1. logic when the contents of the validation function are "wrong schema", which would result in a error message such as "Error, the schema selected was "_templateType_" but the submitted schema is _submittedComponent_". 
**edited to add**: this should cover when someone didn't select the matching template type (e.g. left on default scRNAseq 1) 

There is a separate but related problem also when they upload an out of date template (breaking/non breaking changes have been added)

- [ ] 2. logic to highlight the Component in the Metadata Preview box. 

@milen-sage is the submitted component type returned in the validation step?

**Comment by milen-sage** [comment] 2020-07-09 15:52
When we try validating manifests that were submitted using a previous version of a schema we get the "wrong schema" error in addition to a message saying "An error has occurred. Check your logs or contact the app author for clarification." This isn't a situation that most people would encounter once the schemas are finalized (we mostly encounter it since we and others have been testing with schemas that were still in flux), but I agree we should have better error handling.

It's fine to indicate that the schema used by a manifest is not the right one (i.e. it's wrong) given the selected schema in step 1. But we probably shouldn't be getting "Check your logs..." error. 

The message "At row 2 value Wrong schema in Wrong schema <<column name>> is a required property", can be changed (which is probably the intent of this issue :). If the backend returns "wrong schema", we shouldn't try to interpret at which row and which value the error occurred. Perhaps an informative message would be "The submitted manifest doesn't contain required columns: <<column1, column2, column2>>. Please check that you have selected the correct template type and  ensure your template contains the required columns"; the header row in the preview table can be highlighted with the bright yellow we already use for validation errors.

Once we start versioning schemas and including the version information with the metadata we can have more informative messages, but for now this could be ok?

**Comment by milen-sage** [comment] 2021-01-05 23:55
> @milen-sage is the submitted component type returned in the validation step?

Right now it is not, but it's one line to add the validation target component type here:

https://github.com/Sage-Bionetworks/schematic/blob/ecf6fbdbfceb29268e3183ba9c09401b6454f531/schematic/models/metadata.py#L215
(it corresponds to the rootNode parameter in the method^). 

In two lines, we can also return the component found in the annotations manifest (if the Component column is in the manifest); so that if there is difference between the intended component (in the manifest) and the selected component (in the data curator app); we'd know.

@xdoan and @rrchai can reticulate deal with multiple return variables in Python? If not, we can return the component(s) as part of the errors array.

**Comment by xdoan** [comment] 2021-01-12 22:20
@milen-sage what do you mean by multiple return values? You could return an object or a list as nested as you want, just not a dictionary.

**Comment by milen-sage** [comment] 2021-01-12 23:05
multiple values in this sense https://note.nkmk.me/en/python-function-return-multiple-values/

we can just add the info to the list.

**Comment by xdoan** [comment] 2021-01-13 00:13
oh if its a tuple R has that as well

**Comment by xdoan** [comment] 2021-02-03 21:22
@milen-sage any ideas on the timeline for this feature on the backend? @rrchai is prototyping some code and it would be useful to have to option to show the submitted vs selected template type in the text.

**Comment by milen-sage** [comment] 2021-02-03 23:03
Hi @sujaypatil96 could you take a look at the discussion above?

Could you take on adding code to the manifest  validator that compares the rootNode/component to the component in a manifest and returns an error, as outlined above, if the two do not match?

**Comment by xdoan** [comment] 2021-02-04 21:08
@rrchai edited the scope of this problem to be more specific and cover one specific use-case! See first comment and edited name. lmk if you have any thoughts on this!

**Comment by milen-sage** [comment] 2021-02-08 18:22
@sujaypatil96 a bit of clarification:

This should be fairly minor the way the issue is scoped:
- suppose a user selects metadata template X from the DC app dropdown 
- suppose they mistakenly upload manifest for metadata matching template Y
- we want to return an error along the lines of “Submitted metadata for component Y, but requested validation for component X. Cannot complete validation.”

One way to handle this is to look in the submitted manifest, and check if there is a ‘Component’ column in it; if there is, we can check if the rootNode provided in the validation function matches the component indicated in the ‘Component’ column of the manifest. If they don’t match we return the above error. If there is no ‘Component’ column in the manifest, we just return whatever output the validator currently returns.

**Comment by sujaypatil96** [comment] 2021-02-10 00:10
Closing, since [PR #404](https://github.com/Sage-Bionetworks/schematic/pull/404) resolves this issue.

**Closed** 2021-03-15 20:03 UTC
Labels: feature, good first issue, infrastructure
