### ISSUE TITLE
Quote in Component Column, manifest validation failure

### ISSUE THREAD

**Issue by mialy-defelice** [Sage-Bionetworks/data_curator#224] opened 2021-11-10 20:55 UTC
**Describe the bug**
- [ ] Server disconnect
- [ ] Wrong manifest
- [x] Wrong values in manifest columns
- [ ] Other (please describe)

**To Reproduce**
Center: Stanford
Template: Molecular Test
[https://docs.google.com/spreadsheets/d/1uTpcAVzQ67479xx7Cf2gPQ4lNWTzWoQBHIlT3qS85RY/edit#gid=0](url)

**Screenshots (optional)**
<img width="1672" alt="Screen Shot 2021-11-10 at 12 53 22 PM" src="https://user-images.githubusercontent.com/85905780/141191899-9b46f5de-8817-407c-aebf-1dbef7597ccd.png">

**Additional context (optional)**
Says there is a " in the Component column. Cant seem to find one.

**Comment by rrchai** [comment] 2021-11-22 16:38
@mialy-defelice  Thanks for creating this issue.

I think it is the expected behavior. The app will exclude the empty row, but the row 3 is not empty because there are some values in the `Test Analyte Type`, `Variant Origin`, etc.

**Comment by rrchai** [comment] 2021-11-22 16:39
Close this issues now, but feel free to reopen if you have further questions/suggestions.

**Closed by rrchai** 2021-11-22 16:39 UTC
Labels: Bug Bash v1
